version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env.production
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: postgres
    ports:
      - "${DATABASE_PORT}:5432"

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    env_file:
      - ./.env.production
    environment:
      PORT: ${PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: postgres
      DATABASE_TYPE: ${DATABASE_TYPE}
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    depends_on:
      - postgres
