version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ./.env
    container_name: postgres
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: nest-app
    volumes:
      - .:/app
    environment:
      PORT: ${PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_TYPE: ${DATABASE_TYPE}
    env_file:
      - ./.env
    expose:
      - ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
